### ISSUE TITLE
Remove 1px black border around viewport

### ISSUE THREAD

**Issue by 6C3C41** [bryanhanson/HiveR#12]
Irritating if bkgd = transparent

grid.rect(gp = gpar(fill = bkgnd)) -> grid.rect(gp = gpar(col = NA, fill = bkgnd))

thank you for this wonderful tool!

**Comment by bryanhanson** [comment]
Can you provide an example where this affects your hive plots?  I get the idea, but I don't see it on the quartz device or pdf device on OSX.

**Comment by 6C3C41** [comment]
https://www.dropbox.com/s/5pm03zpbffwgf52/20160304_193007_Screenshot_2016_03_04_19.30.07.png?dl=0

idea is with transparent background for presentation or whatever, don't want to post-hoc crop out back border if unwanted.

**Comment by bryanhanson** [comment]
OK, I had to experiment a bit, but I see what you are talking about.  I wonder if there has been some change to defaults in grid or the graphics devices.  I have done dozens of these and put them into presentations and not seen the border.  I'll try to fix in the near future.  Thanks for the report.

**Comment by 6C3C41** [comment]
I did some quick reading when fixing the issue on my fork and I do believe there were some recent <6mo modifications in grid.rect defaults. Let me know if I can help implement the change or do some testing for you. And thanks again for this extremely useful interface for hive plots, which I'm quite enamored with.

**Comment by bryanhanson** [comment]
Fixed via [716385a](https://github.com/bryanhanson/HiveR/commit/716385a9d90447a2e6c0034e65c44f7b1067c527).  Thanks again for pointing this out.
