### ISSUE TITLE
Adapting weighted networks (WGCNA) for use with HiveR?

### ISSUE THREAD

**Issue by jolespin** [bryanhanson/HiveR#13]
Incredible package you've developed and I am eager to try it out!  I've been transitioning to weighted networks from unweighted networks and have been creating weighted networks using WGCNA.  In weighted networks, everything is connected and most connections are loosely connected.  

My question, have you dealt with the large amount of connections in weighted networks in the context of Hive plots? I was wondering if you're aware of any tutorials that adapt weighted networks to Hive plot visualization.  Do they typically use cutoffs for connecting nodes?  I'm dealing with 4,336 nodes and 9,398,280 non-redundant edges.

**Comment by bryanhanson** [comment]
Hi Josh… I have no direct experience with the type of networks you describe (I’m not certain what they are either).  As far as the speed of HIveR goes, it takes less than 3 seconds to generate a random hive data set with 5,000 notes and 9e6 edges.  Plotting on the other hand is going to be much slower however,  With 5,000 nodes and 10,000 edges it takes about 80 s to plot on my fairly new MacBook.

Bryan

**Comment by jolespin** [comment]
Thanks for getting back to me Bryan.  I looked into it and I think what people have done is collapse the network clusters into single elements; that drops the dimensionality down substantially.
