### ISSUE TITLE
How to randomly assign nodes to 5 different axis if all nodes are manager nodes

### ISSUE THREAD

**Issue by FinScience** [bryanhanson/HiveR#15]
Hi,

Thanks for the awesome hiveR package. One word-beautiful. I am facing a serious trouble though. In my dataset all the nodes are manager nodes, i.e they have both incoming and outgoing edges. Is it possible to randomly assign the nodes to different axis and then draw the hive plot? Would be great if any resolution is there. 

P.S: My dataset has around 50000 edges and 5000 nodes.

**Comment by bryanhanson** [comment]
You should probably think through the nature of the data a bit more: is there any difference between/among what you are calling your manager nodes that would justify putting them on 1 or more additional axes is a rational way?  Usually this is the most-time consuming part of making a hive plot, but it often leads to great insights.  Actually making the hive plot usually ends up being simple.

You certainly could assign to other axes randomly, but that probably won’t be very explanatory.

If you can describe your system a bit, I might be able to make some more specific suggestions, but I’m probably not an expert in whatever you are doing!

Bryan

**Comment by FinScience** [comment]
Hey Bryan,

Thanks for the suggestion. I really don't have much option of thinking about the data as this is the way it is. The data set actually reflects what was the preceding node before coming to the node in concern. To put it simply one node is source and the other is the target. So all the nodes have both incoming and outgoing edges. I tried plotting the data with standard layouts and failed to arrive at something worth displaying. The popular term "hairball plot" was the outcome.  Since I am yet to understand hiveR completely, I tried to force feed my data in the following way and failed miserably. Could you please help me out.

      nodes1 = data.frame(id = 1:6, lab = c("A","B","C","D","E","F"), color = c("yellow", 
         "green","red","yellow","green","red"))

      edges1 = data.frame(id1 = c(1,3,4,5,2,1,6),id2 = c(6,4,3,1,2,3,1), color = 
      c("green","green","green","green","red","blue","orange"))


       nodes1$axis = sample(3,nrow(nodes1), replace = T)

       nodes1$radius = 50
       nodes1$size = 1
       nodes1 = nodes1[,c(1,2,4,5,6,3)]
       edges1$weight = 1

       edges1 = edges1[,c(1,2,4,3)]


       test3 <- ranHiveData(nx = 3)

       test3$nodes = nodes1
       test3$edges = edges1
       test3$desc = "3 axes -- 6 nodes -- 7 edges"

     plotHive(test3)
      *** There seem to be one or more problems with this hive plot data!
      Error in chkHPD(HPD) : 
      Sorry, we can't continue this way: It's not me, it's you!
       In addition: Warning messages:
       1: In chkHPD(HPD) : nodes$lab appears to be corrupt
        2: In chkHPD(HPD) : nodes$color appears to be corrupt

**Comment by bryanhanson** [comment]
You are getting burned by R's sometimes "unique" data typing habits.  If you look at `?HPD` you'll see what types each entry should be.  And `?HEC` shows how to build up a HPD step by step from scratch.  Attached is your script with the necessary fixes.  You did well!

One thing you might consider is to use a 2 axis plot, put everything on one axis, set the unused axis color to transparent or the plot background color.  You'll also need to put one dummy node on the unused axis (see`?HidingAnAxis` for details).  I think that might show the "action" inherent in your data set.  I think all the edges will be on one side of the axis, but somewhere I have an example of how to get them to alternate sides.  If this idea seems to work, I'll dig it up.  Bryan

PS change the extension on the attached file to .R (Gitlab won't accept .R so I used .txt)

[Anon.txt](https://github.com/bryanhanson/HiveR/files/1049989/Anon.txt)

**Comment by FinScience** [comment]
Thanks for pointing out the actions needed. Things seem fine now except that the plot is not getting generated with the following error.

         plotHive(test3)
         Error in valid.viewport(x, y, width, height, just, gp, clip, xscale, yscale,  : 
         invalid 'xscale' in viewport
         In addition: Warning messages:
          1: In max(n2$radius) : no non-missing arguments to max; returning -Inf
          2: In min(n2$radius) : no non-missing arguments to min; returning Inf 

I need to do a few iterations with the actual data to finalize on something concrete(i.e. regarding usage of a single axis) because the volume of data is huge.

**Comment by FinScience** [comment]
Got the resolution. The axis sampling code had created only 1 and 3 but not 2. Hence the error. Thanks for all the help

**Comment by bryanhanson** [comment]
Great, let me know any additional questions!

**Comment by FinScience** [comment]
Hey Bryan,

The plot is not coming due to the error I have shared.
              Error in calcCurveGrob(x, x$debug) : end points must not be identical.

Any ideas?

**Comment by bryanhanson** [comment]
That means there is an edge that begins and ends at the same node, which is impossible to draw.

Use

sumHPD(HPD_object, chk.sm.pt = TRUE)

to find out which one(s).

?sumHPD has some other detailed checks you can run too.

Bryan

**Comment by FinScience** [comment]
I am doing something seriously wrong here. Tried to do the following and still ending up with issue.


               test3$edges = dplyr::filter(test3$edges, id1!=id2)

This also showed the same problem.

Next attempt.

                test3 = mineHPD(test3, option = "remove self edge")
                Error in Ops.factor(fd$n1.lab, fd$n2.lab) : 
                level sets of factors are different

**Comment by bryanhanson** [comment]
I'm not by my computer right now, but it sounds like maybe the data types of gotten screwed up again. Instead of dplyr just try doing a standard subset and see if that works.

**Comment by FinScience** [comment]
Cool. Would be great if you could let me know my error once you get time and access to your computer

**Comment by bryanhanson** [comment]
Hmm… we’ll, it’s not the dplyr call (I thought it might be stomping on data types but it isn’t).

The error is coming from the internals of function “which” and suggest a data type problem, but I don’t see it.

If you do

sumHPD(test3, plot.list = TRUE)

you’ll see everything it plans to plot.  If you do:

sumHPD(test3, chk.sm.pt = TRUE)

you’ll see the self-edges which are the problem.

Maybe with a manual inspection we can see we are dropping something that we needed to keep.  Small artifiical data sets often reveal hidden bugs, so I’ll pursue this but it may not be until tomorrow that I can give it enough time.

In the meantime, if you find something, let me know.

Bryan

**Comment by FinScience** [comment]
Thanks for your time. Would be great if you are able to resolve this. I will definitely share anything I feel might be useful for you to get this resolved.

**Comment by bryanhanson** [comment]
Alright, I think this is fixed.

There were 2 problems.  One related to a change in how base R handled factors.  The other was more tricky and embarassing.  When checking for “self-edges” which cannot be drawn, I was only checking for edges being drawn to/from the same node label / node ID.  However, in the little data set you made, there were what I am now calling “virtual self-edges” which were edges from two different nodes with different labels and IDs but the same axis at the same radius, so they cannot be drawn either.

If this works for you, I need to make sumHPD disintinguish between these two types of self-edges because the first one has a very different conceptual meaning and origin than the second.

Get the updated code via:

library("devtools")
install_github(repo = "bryanhanson/HiveR@devel")

and let me know how it works for you.

Bryan

**Comment by FinScience** [comment]
Hey Bryan,
Thanks for the update. Just need to ask one question that may help me decide whether hive plot is ideal for my dataset. Can nodes on the same axis have edges connecting them? My understanding from your response says NO. Can you please confirm. If that is the case, is there any workaround for situations like this?

**Comment by bryanhanson** [comment]
Yes, nodes on a single axis can be connected by edges provided they have different radii.  If the have the same radii then the edge can’t be drawn — that’s one of the errors your test3 data set was throwing until self edges were removed.

The default behavior will put  all edges that start / end on the same axis on one “side” of the same axis, but one can get the on opposite sides by selectively inverting the from / to nodes.  I can show you that once you get there, if you go there.

Does the repaired function work with your data?

Bryan

**Comment by FinScience** [comment]
It is working with the dummy data absolutely fine. Need to go through some process of making the actual data ideal for plotting. Shall confirm by EOD.

**Comment by FinScience** [comment]
It is working fine. Need to somehow manipulate the data to get the beauty in the plots. The beauty factor is way missing.Since most of my edges would be between nodes on same axis, things are not seeming pretty.  Thanks for all your help and support. It was great interacting with you. Keep up the great work.
