### ISSUE TITLE
Issues with dot2HPD

### ISSUE THREAD

**Issue by GeraldSingh** [bryanhanson/HiveR#9]
I'm having trouble using the dot2HPD command. I wrote a .dot file for a network and a .csv file classifying the edge types but I keep running into an error.

Even when I downloaded the .dot and .csv files of the example of the E coli gene regulation network, I get the same error message. The error message is

Error in if ((tv[1] == ei$dot.tag[k]) & (tv[2] == ei$dot.val[k])) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In readLines(file, ...) : 
  incomplete final line found on 'network_tf_gene.parsed.dot'

I'm running the newest verion of R (3.0.3)

**Comment by jolespin** [comment]
I'm currently running ```‘0.2.55’``` and I received a similar error:
```
> EC1 = dot2HPD(file = "./test_data/network_tf_gene.parsed.dot" ,
+               node.inst=NULL,
+               edge.inst= "./test_data/EdgeInst.csv",
+               desc = "E coli gene regulatory network",
+               axis.cols = rep("grey",3))
No node instructions provided, proceeding without them
Error in if ((tv[1] == ei$dot.tag[k]) & (tv[2] == ei$dot.val[k])) { : 
  argument is of length zero
In addition: Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
```
However, this ran perfectly for me:
```EC1<-dot2HPD(file = system.file("extdata", "E_coli", "E_coli_TF.dot", package = "HiveR"),
node.inst = NULL,
edge.inst = system.file("extdata", "E_coli", "EdgeInst_TF.csv", package = "HiveR"), 
desc = "E coli gene regulatory network (RegulonDB)", axis.cols=rep("grey",3))
sumHPD(EC1)
```
Is the main source of the problem the `dot` file you think? Do you have any recommendations when using custom data?

**Comment by bryanhanson** [comment]
I imagine the immediate problem is the message R gave you:

```
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
```
So there is something goofed up in the file itself.  Open it up in a plain text editor and see if anything stands out.  You might just try reading the file in directly too, it should give that error.  If you want me to look at it, please attach the file.
